package org.techotakus.rider.metal.psi

import com.intellij.psi.tree.IElementType
import org.techotakus.rider.metal.MetalLanguage

object MetalTypes {
    // Basic types usually generated by Grammar-Kit but we define manually for simple cases
    // Currently relying on MetalTokenTypes
}
